export interface SpeciesBehaviorProfile {
  scientific_name: string;
  common_name: string;
  temp_range_c: [number, number];
  temp_optimal_c: [number, number];
  light_preference: 'dawn_dusk' | 'daytime' | 'night' | 'any';
  wind_tolerance: 'calm' | 'light' | 'moderate' | 'any';
  pressure_preference: 'falling' | 'stable' | 'rising' | 'any';
  depth_preference: 'shallow' | 'mid' | 'deep' | 'any';
  moon_sensitivity: 'high' | 'medium' | 'low';
}

export const SPECIES_BEHAVIORS: SpeciesBehaviorProfile[] = [
  {
    scientific_name: 'Micropterus salmoides',
    common_name: 'Largemouth Bass',
    temp_range_c: [10, 32],
    temp_optimal_c: [18, 27],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'moderate',
    pressure_preference: 'falling',
    depth_preference: 'shallow',
    moon_sensitivity: 'medium',
  },
  {
    scientific_name: 'Micropterus dolomieu',
    common_name: 'Smallmouth Bass',
    temp_range_c: [8, 28],
    temp_optimal_c: [15, 24],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'moderate',
    pressure_preference: 'stable',
    depth_preference: 'mid',
    moon_sensitivity: 'medium',
  },
  {
    scientific_name: 'Oncorhynchus mykiss',
    common_name: 'Rainbow Trout',
    temp_range_c: [4, 22],
    temp_optimal_c: [10, 18],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'calm',
    pressure_preference: 'stable',
    depth_preference: 'mid',
    moon_sensitivity: 'low',
  },
  {
    scientific_name: 'Salmo trutta',
    common_name: 'Brown Trout',
    temp_range_c: [3, 22],
    temp_optimal_c: [10, 16],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'calm',
    pressure_preference: 'falling',
    depth_preference: 'mid',
    moon_sensitivity: 'low',
  },
  {
    scientific_name: 'Salvelinus fontinalis',
    common_name: 'Brook Trout',
    temp_range_c: [2, 20],
    temp_optimal_c: [8, 16],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'calm',
    pressure_preference: 'stable',
    depth_preference: 'shallow',
    moon_sensitivity: 'low',
  },
  {
    scientific_name: 'Ictalurus punctatus',
    common_name: 'Channel Catfish',
    temp_range_c: [10, 32],
    temp_optimal_c: [21, 27],
    light_preference: 'night',
    wind_tolerance: 'any',
    pressure_preference: 'any',
    depth_preference: 'deep',
    moon_sensitivity: 'high',
  },
  {
    scientific_name: 'Esox lucius',
    common_name: 'Northern Pike',
    temp_range_c: [6, 28],
    temp_optimal_c: [14, 22],
    light_preference: 'daytime',
    wind_tolerance: 'moderate',
    pressure_preference: 'falling',
    depth_preference: 'shallow',
    moon_sensitivity: 'low',
  },
  {
    scientific_name: 'Esox masquinongy',
    common_name: 'Muskellunge',
    temp_range_c: [8, 28],
    temp_optimal_c: [16, 24],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'moderate',
    pressure_preference: 'falling',
    depth_preference: 'mid',
    moon_sensitivity: 'medium',
  },
  {
    scientific_name: 'Sander vitreus',
    common_name: 'Walleye',
    temp_range_c: [4, 26],
    temp_optimal_c: [12, 20],
    light_preference: 'night',
    wind_tolerance: 'moderate',
    pressure_preference: 'stable',
    depth_preference: 'mid',
    moon_sensitivity: 'high',
  },
  {
    scientific_name: 'Perca flavescens',
    common_name: 'Yellow Perch',
    temp_range_c: [5, 26],
    temp_optimal_c: [14, 22],
    light_preference: 'daytime',
    wind_tolerance: 'light',
    pressure_preference: 'stable',
    depth_preference: 'mid',
    moon_sensitivity: 'low',
  },
  {
    scientific_name: 'Cyprinus carpio',
    common_name: 'Common Carp',
    temp_range_c: [8, 32],
    temp_optimal_c: [18, 26],
    light_preference: 'daytime',
    wind_tolerance: 'any',
    pressure_preference: 'stable',
    depth_preference: 'shallow',
    moon_sensitivity: 'medium',
  },
  {
    scientific_name: 'Oncorhynchus tshawytscha',
    common_name: 'Chinook Salmon',
    temp_range_c: [4, 20],
    temp_optimal_c: [8, 16],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'moderate',
    pressure_preference: 'falling',
    depth_preference: 'deep',
    moon_sensitivity: 'medium',
  },
  {
    scientific_name: 'Thunnus thynnus',
    common_name: 'Atlantic Bluefin Tuna',
    temp_range_c: [10, 28],
    temp_optimal_c: [16, 24],
    light_preference: 'daytime',
    wind_tolerance: 'any',
    pressure_preference: 'stable',
    depth_preference: 'deep',
    moon_sensitivity: 'low',
  },
  {
    scientific_name: 'Morone saxatilis',
    common_name: 'Striped Bass',
    temp_range_c: [8, 26],
    temp_optimal_c: [14, 22],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'moderate',
    pressure_preference: 'falling',
    depth_preference: 'mid',
    moon_sensitivity: 'medium',
  },
  {
    scientific_name: 'Sciaenops ocellatus',
    common_name: 'Red Drum',
    temp_range_c: [10, 30],
    temp_optimal_c: [18, 26],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'moderate',
    pressure_preference: 'falling',
    depth_preference: 'shallow',
    moon_sensitivity: 'high',
  },
  {
    scientific_name: 'Coryphaena hippurus',
    common_name: 'Mahi-Mahi',
    temp_range_c: [20, 32],
    temp_optimal_c: [24, 28],
    light_preference: 'daytime',
    wind_tolerance: 'any',
    pressure_preference: 'stable',
    depth_preference: 'deep',
    moon_sensitivity: 'low',
  },
  {
    scientific_name: 'Lepomis macrochirus',
    common_name: 'Bluegill',
    temp_range_c: [10, 32],
    temp_optimal_c: [20, 28],
    light_preference: 'daytime',
    wind_tolerance: 'calm',
    pressure_preference: 'stable',
    depth_preference: 'shallow',
    moon_sensitivity: 'low',
  },
  {
    scientific_name: 'Pomoxis nigromaculatus',
    common_name: 'Black Crappie',
    temp_range_c: [8, 28],
    temp_optimal_c: [16, 24],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'calm',
    pressure_preference: 'stable',
    depth_preference: 'mid',
    moon_sensitivity: 'medium',
  },
  {
    scientific_name: 'Lutjanus campechanus',
    common_name: 'Red Snapper',
    temp_range_c: [16, 30],
    temp_optimal_c: [20, 26],
    light_preference: 'daytime',
    wind_tolerance: 'moderate',
    pressure_preference: 'stable',
    depth_preference: 'deep',
    moon_sensitivity: 'low',
  },
  {
    scientific_name: 'Centropomus undecimalis',
    common_name: 'Common Snook',
    temp_range_c: [16, 34],
    temp_optimal_c: [24, 30],
    light_preference: 'dawn_dusk',
    wind_tolerance: 'light',
    pressure_preference: 'stable',
    depth_preference: 'shallow',
    moon_sensitivity: 'high',
  },
];

export function getBehaviorProfile(scientificName: string): SpeciesBehaviorProfile | null {
  return SPECIES_BEHAVIORS.find((b) => b.scientific_name === scientificName) ?? null;
}

export function getBehaviorByCommonName(commonName: string): SpeciesBehaviorProfile | null {
  return SPECIES_BEHAVIORS.find((b) => b.common_name === commonName) ?? null;
}

export function getAllBehaviors(): SpeciesBehaviorProfile[] {
  return SPECIES_BEHAVIORS;
}
